### ISSUE TITLE
Как включить дебаг?

### ISSUE THREAD

**Issue by limavrik1** [legend233/yandex_music_downloader#1]
Как понять, почему под Windows не скачивает?

**Comment by legend233** [comment]
Возможно некорректно указан путь для скачивания. Можно попробовать вручную импортировать функцию скачивания артиста и попробовать запустить.

**Comment by limavrik1** [comment]
Это корректно?
download_path = "c:\Ya_music"

**Comment by legend233** [comment]
Без ковычек

**Comment by limavrik1** [comment]
а так скачивания просто по ссылке нет?
def input_data_link(message):
    pass

**Comment by legend233** [comment]
Сделал слияние main из dev. input_data_link не стал делать. В итоге качать можно:

- артиста по названию (так удобнее показалось)
- альбом/сборник по ссылке
- книгу по ссылке
